#config_version=5
#ESCAPE!

# Bathroom mode. 30 seconds to complete bonus mode.

mode:
    start_events:
        bathroom_mode_start
    stop_events:
        timer_bathroom2_mode_countdown_complete
        bathroom2_mode_complete
        timer_bathroom2_mode_countdown_stopped
    priority: 300

sequences:
    bathroom_mode:
        events:
            drop_target_bank_2targetbank_down
            s_bath_target_active
        events_when_complete:
            bathroom_mode_complete
            bathroom2_mode_start
    bathroom2_mode:
        enable_events:
            bathroom_mode_complete
        events:
            mode_bonus_drop_target_hit
            s_subway1_active
        events_when_complete:
            bathroom2_mode_complete
            bathroom_bonus_collect

variable_player:
    bathroom_mode_complete:
        score: 5000
    bathroom_bonus_collect:
        score: 100000

slides:
    bathroom_mode_slide:
        - type: text
          text: BATHROOM MODE
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
    bathroom2_mode_slide:
        - type: text
          text: GET THE BONUS!
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00

slide_player:
    mode_bathroom_started:
        bathroom_mode_slide:
            target: lcd
    bathroom_mode_complete:
        bathroom2_mode_slide:
            target: lcd

timers:
    bathroom2_mode_countdown:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
          - event: bathroom_mode_complete
            action: start
          - event: ball_will_end
            action: stop
        start_running: false
