#config_version=4
mode:
    start_events: ball_starting
    priority: 100

slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 100
            #font_name: LLDCL__
          - type: text
            text: PLAYER (number)
            y: 0
            x: 5
            font_size: 20
            #font_name: LLDCL__
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (ball)
            y: 0
            x: right-5
            anchor_x: right
            anchor_y: bottom
            font_size: 20
            #font_name: LLDCL__

# scoring:
    s_a_lane_active:
        score: 1000
    s_around_scoop_active:
        score: 1000
#     s_attic_drop_kicker_active:
#         score: 10000
#     s_attic_drop_ramp_active:
#         score: 100
#     s_attic_enter_active:
#         score: 1000
#     s_bath_enter_active:
#         score: 1000
    s_bath_target_active:
        score: 1000
    s_c_lane_active:
        score: 1000
#     s_captive_ball_active:
#         score: 1000
    s_cative_target_active:
        score: 10000
#     s_door_target_active:
#         score: 1000
    s_droptargetbank1_active:
        score: 1000
    s_droptargetbank2_active:
        score: 1000
    s_left_inlane_active:
        score: 1000
    s_left_outlane_active:
        score: 100
    s_left_slingshot_active:
        score: 1000
    s_p_lane_active:
        score: 1000
    s_popbumper1_active:
        score: 1000
    s_popbumper2_active:
        score: 1000
    s_popbumper3_active:
        score: 1000
    s_quiet_target_active:
        score: 10000
    s_ramp_target1_active:
        score: 1000
    s_ramp_target2_active:
        score: 1000
    s_ramp_target3_active:
        score: 1000
    s_ramp_target4_active:
        score: 1000
    s_right_inlane_active:
        score: 1000
    s_right_outlane_active:
        score: 100
    s_right_slingshot_active:
        score: 1000
    s_s_lane_active:
        score: 1000
    s_scoop_vuk_active:
        score: 500
    s_singledrop_active:
        score: 1000
    s_spinner_active:
        score: 1000
    s_spiral_enter_active:
        score: 1000
#     s_spiral_kicker_active:
#         score: 1000
#     s_subway1_active:
#         score: 100
#     s_subway2_active:
#         score: 100
#     s_subway3_active:
#         score: 100
    s_upper_slingshot_active:
        score: 1000
#     s_vent_enter_active:
#         score: 1000
    left_orbit_hit:
        score: 10000
#     right_orbit_hit:
#         score: 10000
#     center_orbit_hit:
#         score: 10000
    left_ramp_hit:
        score: 10000
    attic_ramp_hit:
        score: 10000
