#config_version=5
#ESCAPE!

# upstairs mode. 30 seconds to complete bonus mode.

mode:
    start_events:
        upstairs_mode_start
    restart_on_next_ball: true
    stop_events:
        timer_upstairs2_mode_countdown_complete
        upstairs2_mode_complete
        timer_upstairs2_mode_countdown_stopped
    priority: 300

counters:
    upstairs_mode:
        count_events:
            left_ramp_hit
        starting_count: 0
        count_complete_value: 3
        direction: up
        persist_state: true
        events_when_complete:
            upstairs_mode_complete
            upstairs2_mode_start
sequences:
    upstairs2_mode:
        enable_events:
            upstairs_mode_complete
        events:
            mode_bonus_drop_target_hit
            s_subway1_active
        events_when_complete:
            upstairs_bonus_collect
            upstairs2_mode_complete

variable_player:
    upstairs_bonus_collect:
      score: 100000

slides:
    upstairs_mode_slide:
        - type: text
          text: UPSTAIRS MODE
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
    upstairs2_mode_slide:
        - type: text
          text: GET THE BONUS!
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00

slide_player:
    mode_upstairs_started: upstairs_mode_slide
    mode_upstairs2_started: upstairs2_mode_slide

timers:
    upstairs2_mode_countdown:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
          - event: upstairs_mode_complete
            action: start
          - event: ball_will_end
            action: stop
        start_running: false
