#config_version=5
#ESCAPE!

# Revenge Wizard mode. 3 Ball Multiball.

mode:
    start_events:
        revenge_mode_start
    stop_events:
        timer_mode_countdown_complete
        drain
    priority: 300

timers:
    mode_countdown:
        start_value: 30
        end_value: 0
        direction: down
        start_running: true