#config_version=5
#ESCAPE!

# basement mode. 30 seconds to complete bonus mode.

mode:
    start_events:
        basement_mode_start
    stop_events:
        timer_basement2_mode_countdown_complete
        basement2_mode_complete
        timer_basement2_mode_countdown_stopped
    priority: 300

sequences:
    basement_mode:
        events:
            s_basement_enter_active
            balldevice_bd_basement_kicker_ejecting_ball
        persist_state: true
        events_when_complete:
            basement_mode_complete
            basement2_mode_start
    basement2_mode:
        enable_events:
            basement_mode_complete
        events:
            mode_bonus_drop_target_hit
            s_subway1_active
        events_when_complete:
            basement_bonus_collect
            basement2_mode_complete

variable_player:
    basement_bonus_collect:
      score: 100000

slides:
    basement_mode_slide:
        - type: text
          text: BASEMENT MODE
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
    basement2_mode_slide:
        - type: text
          text: GET THE BONUS!
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00

slide_player:
    mode_basement_started: basement_mode_slide
    mode_basement2_started: basement2_mode_slide

timers:
    basement2_mode_countdown:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
          - event: basement_mode_complete
            action: start
          - event: ball_will_end
            action: stop
        start_running: false
