#config_version=5
#ESCAPE!

sound_system:
    buffer: 1024
    frequency: 44100
    channels: 2
    master_volume: 10.0
    tracks:
        voice:
            volume: 0.8
            simultaneous_sounds: 1
            preload: yes
        sfx:
            volume: 0.8
            simultaneous_sounds: 8
            preload: yes
        music:
            volume: 5.0
            simultaneous_sounds: 1

assets:
    sounds:
        default:
            load: on_demand
        voice:
            load: preload
            track: voice
        sfx:
            load: preload
            track: sfx
        music:
            load: preload
            track: music


sounds:
    BG1:
        target: music
        events_when_looping: Background_looping
        events_when_played: Background_played
        events_when_stopped: Background_stopped

    Drain:
        track: sfx
    Ticks:
        track: sfx
