#config_version=4
#Escape!

config:
- hardware.yaml
- display.yaml
- modes.yaml
# Comment keys.yaml out in psyical machine
- keys.yaml
- audio.yaml

game:
    balls_per_game: 3
    max_players: 4
