#config_version=5
#ESCAPE!

config:
- hardware.yaml
- display.yaml
- lights.yaml
- modes.yaml
# Comment out keys.yaml on psyical machine
#- keys.yaml
- audio.yaml

game:
    balls_per_game: 3
    max_players: 4