#config_version=4
#Escape!

config:
- hardware.yaml
- display.yaml
- modes.yaml
# Comment out keys.yaml on psyical machine!
- keys.yaml
- audio.yaml

game:
    balls_per_game: 3
    max_players: 4
    # player_controlled_eject_tag: plunge_button