# config_version=4
# ESCAPE!

displays:
    lcd:
        width: 640
        height: 360
        default: yes
    playfield:
        width: 600
        height: 800

window:
    width: 640
    height: 360
    title: Escape! Pinball
    resizable: true
    fullscreen: false
    borderless: false
    exit_on_escape: true
    source_display: lcd

slides:
    window_slide:
        widgets:
          - type: text
            text: ESCAPE!
            bold: true
            font_name: arial
            font_size: 36
          - type: rectangle
            width: 540
            height: 260
            color: Red
          - type: image
            image: bg3_2

slide_player:
    mc_reset_phase_1:
        window_slide:
            target: lcd