#config_version=5
#ESCAPE!


hardware:
    platform: p_roc
    driverboards: pdb

switches:
    ##########################################################################
    # Using 32 direct switches and 8x8 (64 switches) matrix
    # NOTE: Opto switches must use Direct switches
    # Direct Switches, SD0 - SD31
    # name:
    #   number: <number>
    #           <number> can be: SDx (x is the switch number) or switch matrix number
    #           Direct Switches: P-ROC switch # = SDx
    #           Remember numbers start at 0 "zero" and the Key Pin is not counted
    #           Bank B switch: P3-ROC switch # = SW-16 address * 16 + 8 + Bank B switch input
    #   type: <type>
    #         <type> 'NO' (normally open.  This is the default; so no need to use this)
    #                'NC' (normally closed.  Common for optos)?
    #   tags: <group>
    #   ballsearch: reset, stop(prevent counter from starting)
    #   debounce: auto(default), quick, normal
    #
    # Switch matrix switch numbers are entered using the column number, then a slash, then the row number.
    # Matrix switches, 0/0 - 7/7
    #   number: 0/0  # column 0, row 0
    ##########################################################################
    ###################################
    # P-Roc Direct Switch Inputs # J6 #
    # SD0,SD1,SD2  are optic switches #
    ###################################
    s_left_ramp_top:
        number: SD0
        tags:
        label:
        type: NC
    s_left_ramp_center:
        number: SD1
        tags:
        label:
        type: NC
    s_right_orbit:
        number: SD2
        tags:
        label:
        type: NC
    s_upper_slingshot:
        number: SD3
        tags:
        debounce: quick
        label:
    s_ramp_target4:
        number: SD4
        tags:
        label:
    s_ramp_target3:
        number: SD5
        tags:
        label:
    s_ramp_target2:
        number: SD6
        tags:
        label:
    s_ramp_target1:
        number: SD7
        tags:
        label:

    ####################################
    # P-Roc Direct Switch Inputs # J15 #
    ####################################
    s_left_flipper:
        number: SD8
        label: Left Flipper Button
    s_right_flipper:
        number: SD9
        label: Right Flipper Button
    s_left_slingshot:
        number: SD10
        tags:
        debounce: quick
        label: Left Sling
    s_right_slingshot:
        number: SD11
        tags:
        debounce: quick
        label: Right Sling
    s_left_inlane:
        number: SD12
        tags: playfield_active
        label: Left Inlane
    s_right_inlane:
        number: SD13
        tags:
        label: Right Inlane
    s_left_outlane:
        number: SD14
        tags: drain
        label: Left Outlane
    s_right_outlane:
        number: SD15
        tags: drain
        label: Right Outlane

    ####################################
    # P-Roc Direct Switch Inputs # J33 #
    ####################################
    s_start:
        number: SD16
        tags: start
        label: Start Button
    s_popbumper1:
        number: SD17
        tags:
        debounce: quick
        label:
    s_popbumper2:
        number: SD18
        tags:
        debounce: quick
        label:
    s_popbumper3:
        number: SD19
        tags:
        debounce: quick
        label:
    s_singledrop:
        number: SD20
        tags:
        label: Single Drop Target
    s_drop_target_bank1:
        number: SD21
        tags:
        label: Drop Target Bank 1
    s_drop_target_bank2:
        number: SD22
        tags:
        label: Drop Target Bank 2
    s_scoop_VUK:
        number: SD23
        tags:
        label: VUK

    ####################################
    # P-Roc Direct Switch Inputs # J25 #
    ####################################
    s_trough1:
        number: SD24
        label: Trough 1
        debounce: quick
    s_trough2:
        number: SD25
        debounce: quick
        label: Trough 2
    s_trough3:
        number: SD26
        debounce: quick
        label: Trough 3
    s_trough4:
        number: SD27
        debounce: quick
        label: Trough 4
    s_basement_kicker:
        number: SD28
        label: basement Kicker
    s_ball_release:
        number: SD29
        label: Subway Ball Release
    s_right_flipper_upper:
        number: SD30
        label: Right Upper Flipper Button
    s_plunger_lane:
        number: SD31
        label: Plunger Lane

    ####################################
    # P-Roc Matrix Switch Inputs column 0, row 0-7
    # #J19 pins 1 is output for all column 0 switches#
    # #J22 Pins 1-5, 7-9 are input for rows 0-7#
    ####################################

# Martix Block 1

    s_bath_target:
        number: 0/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_left_orbit:
        number: 1/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_basement_enter:
        number: 2/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_skillsave:
        number: 3/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_s_lane:
        number: 4/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_c_lane:
        number: 5/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_a_lane:
        number: 6/0
        tags:
        debounce: quick #or normal or auto
        label:
    s_p_lane:
        number: 7/0
        tags:
        debounce: quick #or normal or auto
        label:

# Martix block 2

    s_left_ramp_enter:
        number: 0/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_spinner:
        number: 1/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_captive_target:
        number: 2/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_quiet_target:
        number: 3/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_right_ramp_enter:
        number: 4/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_around_scoop:
        number: 5/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_center_orbit:
        number: 6/1
        tags:
        debounce: quick #or normal or auto
        label:
    s_right_ramp_top:
        number: 7/1
        tags:
        debounce: quick #or normal or auto
        label:

# Martix block 3

    s_subway1:
        number: 0/2
        tags:
        debounce: quick #or normal or auto
        label:
    s_vent_enter:
        number: 1/2
        tags:
        debounce: quick #or normal or auto
        label:
    s_subway2:
        number: 2/2
        tags:
        debounce: quick #or normal or auto
        label:
#     s_:
#         number: 3/2
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 4/2
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 5/2
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 6/2
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 7/2
#         tags:
#         debounce: quick #or normal or auto
#         label:

# Martix block 4

#     s_:
#         number: 0/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 1/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 2/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 3/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 4/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 5/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 6/3
#         tags:
#         debounce: quick #or normal or auto
#         label:
#     s_:
#         number: 7/3
#         tags:
#         debounce: quick #or normal or auto
#         label:

coils:
    ##########################################################################
    # Coil numbering format: Ax-By-z:
    # Capital letters are required, lower case letters represent the numbers:
    # x : Board address (0-7)
    # y : Bank address (0 for A, 1 for B)
    # z : Output number (0-7)
    # Remember numbers start at 0 "zero" and the Key Pin is not counted
    ##########################################################################
    #####################################################
    # PD-16/Master # Address:0 # Bank:A # Voltage:70vdc #
    #####################################################
    c_auto_plunge:
        number: A0-B0-0
        default_pulse_ms: 12
        max_pulse_ms: 50
        label: Auto Plunger
    c_trough_eject:
        number: A0-B0-1
        default_pulse_ms: 20
        max_pulse_ms: 50
        label: Trough Eject
    c_flipper_right_upper:
        number: A0-B0-2
        allow_enable: true
        default_pulse_ms: 8
        max_pulse_ms: 50
        default_hold_power: 0.125
        label: Right Upper Flipper
    c_flipper_left_main:
        number: A0-B0-3
        allow_enable: true
        default_pulse_ms: 17
        max_pulse_ms: 50
        default_hold_power: 0.125
        label: Left Flipper
    c_flipper_right_main:
        number: A0-B0-4
        allow_enable: true
        default_pulse_ms: 20
        max_pulse_ms: 50
        default_hold_power: 0.125
        label: Right Flipper
    c_left_slingshot:
        number: A0-B0-5
        default_pulse_ms: 4
        max_pulse_ms: 50
        label: Left Sling
    c_right_slingshot:
        number: A0-B0-6
        default_pulse_ms: 4
        max_pulse_ms: 50
        label: Right Sling
    c_upper_slingshot:
        number: A0-B0-7
        default_pulse_ms: 4
        max_pulse_ms: 50
        label: Upper Sling

  #####################################################
  # PD-16/Master # Address:0 # Bank:B # Voltage:70vdc #
  #####################################################
    c_popbumper1:
        number: A0-B1-0
        default_pulse_ms: 6
        max_pulse_ms: 100
        label: Pop Bumper 1
    c_popbumper3:
        number: A0-B1-1
        default_pulse_ms: 6
        max_pulse_ms: 100
        label: Pop Bumper 3
    c_popbumper2:
        number: A0-B1-2
        default_pulse_ms: 6
        max_pulse_ms: 100
        label: Pop Bumper 2
    c_singledroptarget:
        number: A0-B1-3
        default_pulse_ms: 16
        max_pulse_ms: 100
        label: Single Drop Target
    c_ball_release:
        number: A0-B1-4
        default_pulse_ms: 110
        max_pulse_ms: 110
        label: Ball Release Coil
#    c_Bad Transistor - Do not use:
#        number: A0-B1-5
#        default_pulse_ms: 4
#        max_pulse_ms: 50
#        label: Upper Slingshot
    c_droptargetbank:
        number: A0-B1-6
        default_pulse_ms: 25
        max_pulse_ms: 100
        label: Drop Target Bank
    c_scoop_VUK:
        number: A0-B1-7
        default_pulse_ms: 6
        max_pulse_ms: 100
        label: VUK

  ##############################################
  # PD-16 # Address:1 # Bank:A # Voltage:70vdc #
  # This whole bank may be fried...            #
  # need to investigate#                       #
  ##############################################
    # c_:
    #     number: A1-B0-0
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-1
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-2
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-3
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-4
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-5
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-6
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-7
    #     default_pulse_ms:
    #     label:

  ##############################################
  # PD-16 # Address:1 # Bank:B # Voltage:70vdc #
  ##############################################
    #c_attic_diverter:
    #    number: A1-B1-0
    #    default_hold_power: .25
    #    enable_events: s_attic_enter_active
    #    label: Attic Diverter
    # c_basement_kicker:
    #     number: A1-B1-3
    #     default_pulse_ms: 5
    #     max_pulse_ms: 50
    #     label: Basement Kicker
    # c_:
    #     number: A1-B0-2
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-3
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-4
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-6
    #     default_pulse_ms:
    #     label:
    # c_:
    #     number: A1-B0-7
    #     default_pulse_ms:
    #     label:

autofire_coils:
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot
    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot
    upper_slingshot:
        coil: c_upper_slingshot
        switch: s_upper_slingshot
    popbumper1:
        coil: c_popbumper1
        switch: s_popbumper1
    popbumper2:
        coil: c_popbumper2
        switch: s_popbumper2
    popbumper3:
        coil: c_popbumper3
        switch: s_popbumper3

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        activation_switch: s_right_flipper
    right_upper_flipper:
        main_coil: c_flipper_right_upper
        activation_switch: s_right_flipper_upper

drop_targets:
    targetbank1:
        switch: s_singledrop
        reset_coil: c_singledroptarget
    targetbank2_1:
        switch: s_drop_target_bank1
        reset_coil: c_droptargetbank
    targetbank2_2:
        switch: s_drop_target_bank2
        reset_coil: c_droptargetbank

drop_target_banks:
    2targetbank:
        drop_targets: targetbank2_1, targetbank2_2
        reset_coils: c_droptargetbank
        reset_events:
            bathroom_mode_start
            bathroom2_mode_complete
            ball_end
    1targetbank:
        drop_targets: targetbank1
        reset_coils: c_singledroptarget
        reset_events:
            basement_mode_complete
            bathroom_mode_complete
            kitchen_mode_complete
            quiet_mode_complete
            upstairs_mode_complete
            ball_end

ball_devices:
    bd_trough:
        tags: trough, home, drain
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4
        eject_coil: c_trough_eject
        eject_targets: bd_plunger
    bd_plunger:
        ball_switches: s_plunger_lane
        eject_timeouts: 3s
        mechanical_eject: true
        eject_coil: c_auto_plunge
    bd_scoop:
        ball_switches: s_scoop_VUK
        eject_coil: c_scoop_VUK
        eject_timeouts: 3s
        ball_search_order: 2
    bd_ball_release:
        ball_switches: s_ball_release
        eject_coil: c_ball_release
        eject_timeouts: 3s
        eject_targets: bd_scoop
        ball_search_order: 1
    # bd_basement_kicker:
    #     ball_switches: s_basement_kicker
    #     eject_coil: c_basement_kicker
    #     eject_timeouts: 3s
    #     ball_search_order: 3

#ball_locks:
#    closet_lock:
#        balls_to_lock: 3
#        lock_devices: bd_ball_release

diverters:
    # attic_diverter:
    #     activation_coil: c_attic_diverter
    #     type: hold
    #     activation_time: 5s
    #     activation_switches: s_right_ramp_top
    #     deactivation_switches: s_subway2
    #     enable_events: attic_mode_start
    #     disable_events: attic_mode_complete
    #     ball_search_order: 0    #Don't search this device
    # drop_target:
    #     activation_coil: c_singledroptarget
    #     activation_switches: s_subway1
    #     type: pulse
    #     enable_events:
    #         basement_mode_complete
    #         bathroom_mode_complete
    #         kitchen_mode_complete
    #         quiet_mode_complete
    #         upstairs_mode_complete
    #     disable_events:
    #         basement2_mode_complete
    #         bathroom2_mode_complete
    #         kitchen2_mode_complete
    #         quiet2_mode_complete
    #         upstairs2_mode_complete

playfields:
    playfield:
        default_source_device: bd_plunger
        tags: default
