# config_version=4
# ESCAPE!

modes:
    - base
    - EOB
    - LaunchBall
    - bgmusic
    - attic
    - bathroom
    - closet
    - closetMultiball
    - kitchen
    - quiet
    - runMultiball
    - skillsave
    - skillshot
    - spiral
    - superspinner
    - revenge
    - tilt    