# config_version=4
# ESCAPE!

shots:
  E_lane:
    switch: s_left_inlane
#    show_token:
#      light: l_left_inlane
  S_lane:
    switch: s_S_lane
#    show_token:
#      light: l_s_rollover
  C_lane:
    switch: s_C_lane
#    show_token:
#      light: l_c_rollover
  A_lane:
    switch: s_A_lane
#    show_token:
#      light: l_a_rollover
  P_lane:
    switch: s_P_lane
#    show_token:
#      light: l_p_rollover
  E2_Lane:
    switch: s_right_inlane
#    show_token:
#      light: l_right_inlane
  left_orbit:
    switch_sequence: s_left_orbit, s_center_orbit, s_right_orbit
    time: 3s    
  right_orbit:
    switch_sequence: s_right_orbit, s_center_orbit, s_left_orbit
    time: 3s
  center_orbit:
    switch_sequence: s_skillsave, s_center_orbit, s_right_orbit
    time: 3s
  left_ramp:
    switch_sequence: s_left_ramp_enter, s_left_ramp_center, s_left_ramp_top
    time: 5s
  attic_ramp:
    switch_sequence: s_right_ramp_enter, s_right_ramp_top
    time: 3s

shot_groups:
  rollover_lanes:
    shots: E_lane, S_lane, C_lane, A_lane, P_lane, E2_lane
  