#config_version=5
#ESCAPE!

# Attic mode. 30 seconds to complete.

mode:
    start_events:
        attic_mode_start
    restart_on_next_ball: true
    stop_events:
        attic_mode_complete
    priority: 300

sequences:
    attic_mode:
        events:
          - s_vent_enter_active
          - attic_ramp_hit
          - s_subway2_active
        events_when_complete:
            attic_mode_complete

slides:
    attic_mode_slide:
        - type: text
          text: FALL INTO THE ATTIC VENT
          font_size: 75
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: center
          anchor_y: bottom
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
          font_name: digital-7 (italic).ttf
          color: ffa500
          anchor_x: center
          anchor_y: top
        - type: text
          text: PLAYER (number)
          y: 0
          x: 3
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: BALL (ball)
          y: 0
          x: right-3
          anchor_x: right
          anchor_y: bottom
          font_size: 40
          font_name: FEASFBI_.ttf
          color: ffff00

slide_player:
    mode_attic_started: attic_mode_slide