#config_version=5
#ESCAPE!

# Super Spinner mode.

mode:
    start_events:
        spinner_qualify_complete
    stop_events:
        superspinner_mode_complete
        drain
    priority: 500

sequences:
    superspinner_mode:
        events:
            s_spinner_active
            left_orbit_hit
            s_captive_target_active
        events_when_complete:
            superspinner_mode_complete
            superspinner_bonus_collect
        reset_on_complete: true

widgets:
    superspinner_widget:
        -  type: text
           text: Super Spinner Active
           font_size: 75
           font_name: FEASFBI_.ttf
           color: ffff00
           y: top-5
           anchor_y: top

widget_player:
    mode_superspinner_started: superspinner_widget

variable_player:
    superspinner_bonus_collect:
      score: 100000
