#config_version=5
#ESCAPE!

# SkillSave mode. 10 seconds to complete.

mode:
    start_events:
        skillsave_active
    stop_events:
        skillsave_mode_complete
        timer_skillsave_countdown_complete
        timer_skillsave_countdown_stopped
        ball_will_end
    priority: 200

ball_saves:
    skillsave:
        auto_launch: no
        balls_to_save: 1
        eject_delay: 3s
        label: SkillSave Ball Save

sequences:
    skillsave_mode:
        events:
            s_skillsave_active
            s_skillsave_target_active
        disable_events:
            s_left_slingshot_active
            s_right_slingshot_active
            e_lane_hit
            s_lane_hit
            c_lane_hit
            a_lane_hit
            p_lane_hit
            e2_lane_hit
            s_left_orbit_active
            s_right_orbit_active
        events_when_complete:
            skillsave_mode_complete

event_player:
    skillsave_mode_complete:
        player_ball:
            player_num: 1
            value: 1
            change: -1
            prev_value: 2

timers:
    skillsave_countdown:
        start_value: 10
        end_value: 0
        direction: down
        control_events:
          - action: start
            event: balldevice_bd_plunger_ball_eject_success
          - action: stop
            event: skillsave_mode_disabled
        start_running: false